name: collections_unrelated_types_false_positives
description: A sample command-line application.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.2.3

dependencies:
  file: ^7.0.0
  glob: ^2.1.2


dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
